#pragma once

#define PLUGIN_INCLUDE_LV2
#define DEFAULT_SAMPLE_RATE (48000.0)
#define DEFAULT_MIN_BLOCK_LEN 256
#define DEFAULT_MAX_BLOCK_LEN 1024
#define DEFAULT_SEQ_BUF_SIZE 4096
#define FX_PROCESS_NAME "calicofx"
